image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

dev:
  stage: build
  script:
  - bundle exec jekyll build
  except:
  - master

prod:
  stage: build
  script:
  - bundle exec jekyll build
  only:
  - master
