variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

dev:
  stage: deploy
  script:
  - bundle exec jekyll build
  - rsync --delete -rltoDvP _site/ /var/www/dev.southernmeditation.com
  only:
  - develop

prodbuild:
  stage: deploy
  script:
  - bundle exec jekyll build
  only:
  - master
