variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

devbuild:
  stage: test
  script:
  - bundle exec jekyll build
  - ls -al _site
  only:
  - develop

devdeploy:
  stage: deploy
  script: 
  - rsync --delete -avP _site/ /var/www/dev.southernmeditation.com
  only:
  - develop

prodbuild:
  stage: build
  script:
  - bundle exec jekyll build
  only:
  - master
