image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

dev-build:
  stage: build
  script:
  - bundle exec jekyll build
  except:
  - master

dev-deploy:
  stage: deploy
  script: 
  - rsync --delete -avP _site/ /var/www/dev.southernmeditation.com
  except:
  - master

prod-build:
  stage: build
  script:
  - bundle exec jekyll build
  only:
  - master
