image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: develop
  script:
  - bundle exec jekyll build
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build
  only:
  - master
