# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Southern Meditation
email: iona@southernmeditation.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://southernmeditation.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: southernmeditation
github_username:  bartdorsey
show_excerpts: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


permalink: /podcast/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
podcast_url: http://southernmeditation.com/
podcast_album_art: /assets/images/Podcast-Artwork.jpg
podcast_title: Southern Meditation
podcast_owner: Southern Meditation
podcast_email: iona@southernmeditation.com
podcast_category: Health
podcast_subcategory_one: Self-Help
podcast_subcategory_two: 
podcast_explicit: "no"
podcast_author: Southern Meditation
podcast_description: Welcome to Southern Mediation, a podcast series to help you relax, sleep or focus deeply. While we aren’t medical doctors, and make no medical claims, we understand that taking time for yourself will help you be healthier and happier. We listened to many sleep podcasts, which in essence were fine, but here in the South we don’t much cotton to having folks stacking our Chakras or lining up our Qi. So we created this series with a dash of southern charm and stories that will bring you home, wherever in the world that may be.
podcast_summary: 
podcast_subtitle: 
